// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qHuw_bi2uBEHjAlI3Q-7xtVb7OsWIbU',
    appId: '1:1088108755122:web:d3a816f9835ae946e8b1ab',
    messagingSenderId: '1088108755122',
    projectId: 'minhas-viagens-322501',
    authDomain: 'minhas-viagens-322501.firebaseapp.com',
    storageBucket: 'minhas-viagens-322501.appspot.com',
    measurementId: 'G-BM0LEXSE2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARJGELnJOySYMDXn_YDJXAPLkEOJGK_Ow',
    appId: '1:1088108755122:android:64a4c26e21c81314e8b1ab',
    messagingSenderId: '1088108755122',
    projectId: 'minhas-viagens-322501',
    storageBucket: 'minhas-viagens-322501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgAouGOHdWgsvONw-C1ijYz83CL9vFxzg',
    appId: '1:1088108755122:ios:5b4c8b4f483d242fe8b1ab',
    messagingSenderId: '1088108755122',
    projectId: 'minhas-viagens-322501',
    storageBucket: 'minhas-viagens-322501.appspot.com',
    androidClientId: '1088108755122-vm2r5jacvfkfs61o49mmkajj3h9gas8b.apps.googleusercontent.com',
    iosClientId: '1088108755122-b21c8uoja3kc5i4vsdh9h84ik3gmas4l.apps.googleusercontent.com',
    iosBundleId: 'com.guilhermereis.minhasviagens.minhasViagens',
  );
}
